/**
 * Shared TypeScript types and interfaces.
 */

import type { Cube } from './objects/Cube';

export interface CubeStyle {
  bg: number;
  text: number;
  size: number;
}

export interface CollisionPair {
  bodyA: MatterJS.BodyType;
  bodyB: MatterJS.BodyType;
}

export interface MergeEvent {
  newValue: number;
  x: number;
  y: number;
}

export interface ScoreChangedEvent {
  score: number;
  best: number;
  delta: number;
}

export interface GameOverEvent {
  score: number;
  best: number;
}

/**
 * Internal cube registry used by MergeSystem and GameOverDetector.
 *
 * NOTE: The YandexAdsPlugin interface lives in src/ads/AdsManager.ts,
 * co-located with the registerPlugin() call that consumes it. Keeping them
 * together avoids drift between the TS contract and the native
 * YandexAdsPlugin.java generated by scripts/setup-android.mjs.
 */
export interface CubeRegistry {
  cubes: Set<Cube>;
  registerCube(cube: Cube): void;
  unregisterCube(cube: Cube): void;
}
