/**
 * AdsManager: single entry point for showing ads.
 *
 * Architecture:
 *   - On native Android (Capacitor), uses the `YandexAds` Capacitor plugin
 *     generated by scripts/setup-android.mjs. The plugin wraps Yandex Mobile
 *     Ads SDK 8.x and exposes two methods:
 *       showRewardedAd({ adUnitId }) → resolves { granted: boolean, error?: string }
 *       showInterstitialAd({ adUnitId }) → resolves { shown: boolean, error?: string }
 *     The plugin loads the ad on demand and shows it — there's no separate
 *     preload step (unlike the previous 7.x-based design).
 *   - On the web (browser), falls back to a stub: rewarded returns granted=true,
 *     interstitial is a no-op.
 *
 * Usage:
 *   await AdsManager.getInstance().init();
 *   await AdsManager.getInstance().showRewarded();           // → boolean
 *   await AdsManager.getInstance().showInterstitial();        // → void
 *   await AdsManager.getInstance().maybeShowInterstitialOnDeath(totalDeaths);
 *   await AdsManager.getInstance().maybeShowInterstitialOnMilestone();
 */

import { Capacitor, registerPlugin } from '@capacitor/core';
import { ADS_CONFIG } from '../config';

/**
 * Native plugin contract (matches YandexAdsPlugin.java generated by
 * scripts/setup-android.mjs).
 */
export interface YandexAdsPlugin {
  initialize(): Promise<void>;
  showRewardedAd(options: { adUnitId: string }): Promise<{ granted: boolean; error?: string }>;
  showInterstitialAd(options: { adUnitId: string }): Promise<{ shown: boolean; error?: string }>;
  showBannerAd(options: { adUnitId: string }): Promise<{ shown: boolean; error?: string }>;
  hideBannerAd(): Promise<{ hidden: boolean; error?: string }>;
}

const YandexAds = registerPlugin<YandexAdsPlugin>('YandexAds');

class AdsManager {
  private initialized: boolean = false;
  private lastInterstitialShownAt: number = 0;

  private static instance: AdsManager | null = null;
  static getInstance(): AdsManager {
    if (!AdsManager.instance) AdsManager.instance = new AdsManager();
    return AdsManager.instance;
  }

  /**
   * Initialize the Yandex Mobile Ads SDK. On web this is a no-op.
   * The plugin's load() method already calls YandexAds.initialize() on the
   * Android side, so this JS-side call is mostly for symmetry / future use
   * (e.g. waiting for SDK readiness before requesting ads).
   */
  async init(): Promise<void> {
    if (this.initialized) return;
    if (!Capacitor.isNativePlatform()) {
      console.info('[Ads] Web platform — ads disabled (stub mode).');
      this.initialized = true;
      return;
    }
    try {
      await YandexAds.initialize();
      this.initialized = true;
      console.info('[Ads] Yandex Mobile Ads SDK initialized.');
    } catch (e) {
      console.warn('[Ads] init failed:', e);
    }
  }

  /**
   * Show an interstitial after a death, subject to:
   *   - every `interstitialEveryDeaths`-th death
   *   - minimum gap of `interstitialMinGapMs` between interstitials
   */
  async maybeShowInterstitialOnDeath(totalDeaths: number): Promise<void> {
    if (!Capacitor.isNativePlatform()) return;
    if (totalDeaths % ADS_CONFIG.interstitialEveryDeaths !== 0) return;
    await this.showInterstitialInternal();
  }

  /**
   * Show an interstitial after a milestone dialog is dismissed.
   * Subject only to the minimum-gap rule.
   */
  async maybeShowInterstitialOnMilestone(): Promise<void> {
    if (!Capacitor.isNativePlatform()) return;
    await this.showInterstitialInternal();
  }

  private async showInterstitialInternal(): Promise<void> {
    const now = Date.now();
    if (now - this.lastInterstitialShownAt < ADS_CONFIG.interstitialMinGapMs) {
      console.info('[Ads] Skipping interstitial — too soon after the last one.');
      return;
    }
    try {
      const result = await YandexAds.showInterstitialAd({
        adUnitId: ADS_CONFIG.interstitialAdId,
      });
      if (result.shown) {
        this.lastInterstitialShownAt = Date.now();
        console.info('[Ads] Interstitial shown.');
      } else {
        console.warn('[Ads] Interstitial not shown:', result.error);
      }
    } catch (e) {
      console.warn('[Ads] showInterstitialAd failed:', e);
    }
  }

  /**
   * Show a rewarded ad. Resolves `true` if the user earned the reward,
   * `false` if the ad was skipped, failed to load, or we're on web.
   *
   * On web, returns `true` so the revive button can still be tested.
   */
  async showRewarded(): Promise<boolean> {
    if (!Capacitor.isNativePlatform()) {
      console.info('[Ads] Web stub: granting fake rewarded.');
      return true;
    }
    try {
      const result = await YandexAds.showRewardedAd({
        adUnitId: ADS_CONFIG.rewardedAdId,
      });
      console.info('[Ads] Rewarded result:', result);
      return result.granted === true;
    } catch (e) {
      console.warn('[Ads] showRewardedAd failed:', e);
      return false;
    }
  }

  /**
   * Show a banner ad overlaid at the bottom of the screen.
   * Uses Yandex SDK 8.x adaptive sticky banner — auto-refreshes at the
   * SDK's default interval (≥30s, respects Yandex policy automatically).
   * Call hideBanner() to remove it.
   *
   * On web, this is a no-op.
   */
  async showBanner(): Promise<void> {
    if (!Capacitor.isNativePlatform()) return;
    try {
      await YandexAds.showBannerAd({ adUnitId: ADS_CONFIG.bannerAdId });
      console.info('[Ads] Banner shown.');
    } catch (e) {
      console.warn('[Ads] showBannerAd failed:', e);
    }
  }

  /**
   * Hide the banner ad (if shown). Safe to call multiple times.
   */
  async hideBanner(): Promise<void> {
    if (!Capacitor.isNativePlatform()) return;
    try {
      await YandexAds.hideBannerAd();
      console.info('[Ads] Banner hidden.');
    } catch (e) {
      console.warn('[Ads] hideBannerAd failed:', e);
    }
  }
}

export { AdsManager };
